language: objective-c
osx_image: xcode8
xcode_project: TaxonomyKit.xcodeproj
xcode_scheme: TaxonomyKit
xcode_sdk: iphonesimulator10.0
after_success:
- bash <(curl -s https://codecov.io/bash) -J 'TaxonomyKit'
